name: Omniscient Gold Bot

on:
  schedule:
    # Menggunakan interval 15 menit yang lebih stabil untuk GitHub
    - cron: '*/15 * * * *'
  workflow_dispatch:
    # Memungkinkan kamu menjalankan bot manual dari tombol 'Run Workflow'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          pip install requests pytz

      - name: Run Gold Bot
        env:
          # Menghindari masalah timezone pada sistem GitHub
          TZ: Asia/Jakarta
        run: python bot_emas.py
